In [1]:
import numpy as np
import pandas as pd

In [ ]:
import pandas as pd
dict = {
    "Name" : ["Sabuj","Ram","Subham"],
    "Marks" : [99,68,87],
    "City" : ['kolkata','Naipur','Egra',]
}

df = pd.DataFrame(dict)
df.to_csv('Friend.csv') # the csv file contains indices
df.to_csv('Friend_False_index.csv',index=False) # indices will not be there
df.head(2) # it will prints the first 2 rows 
df.tail(2) # it will print the second 2 rows

# the last call will execute

     Name  Marks    City
1     Ram     68  Naipur
2  Subham     87    Egra

In [ ]:
import pandas as pd
dict = {
    "Name" : ["Sabuj","Ram","Subham"],
    "Marks" : [99,68,87],
    "City" : ['kolkata','Naipur','Egra',]
}
df = pd.DataFrame(dict)
df.head(2) # will show the first two rows
df.tail(2) # will show the last two rows

df.describe() 
# It will print the following data


#          Marks
# count	3.0000000
# mean	84.666667
# std	15.631165
# min	68.000000
# 25%	77.500000
# 50%	87.000000
# 75%	93.000000
# max	99.000000

           Marks
count   3.000000
mean   84.666667
std    15.631165
min    68.000000
25%    77.500000
50%    87.000000
75%    93.000000
max    99.000000

In [7]:
import pandas as pd
car = {
    "Brand" : ["BMW","Audi","Mercedese","Toyota"],
    "Colour" : ["Wine","Black","Red","white"],
    "Model" : ["M4","A3","Benz","Fortunee"]
}

df = pd.DataFrame(car)
df

       Brand Colour     Model
0        BMW   Wine        M4
1       Audi  Black        A3
2  Mercedese    Red      Benz
3     Toyota  white  Fortunee

In [ ]:
import pandas as pd
car = {
    "Brand" : ["BMW","Audi","Mercedese","Toyota"],
    "Colour" : ["Wine","Black","Red","white"],
    "Model" : ["M4","A3","Benz","Fortunee"]
}
# to read the data we use the pd.read_csv method
read = pd.read_csv('Friend.csv')
read

   Unnamed: 0    Name  Marks     City
0           0   Sabuj     99  kolkata
1           1     Ram     68   Naipur
2           2  Subham     87     Egra

In [ ]:
import pandas as pd

friend = {
    'Name' : ['Gouranga Mondal','Debmalya Sau','Sabuj Ghorai'],
    'Age' : [20,20,21],
    'Gender' : ['Male','Male','Female']
}

df = pd.DataFrame(friend)
df.to_csv('friend.csv')

              Name  Age  Gender
0  Gouranga Mondal   20    Male
1     Debmalya Sau   20    Male
2     Sabuj Ghorai   21  Female

In [1]:
import pandas as pd
car = {
    "Brand": ["BMW","AUDI","MUSTANG"],
    "Model": ["M4","A3","GT"],
    "SPeed": ["280","220","350"]
}
df = pd.DataFrame(car)
df.to_csv('newfile.csv')
df

     Brand Model SPeed
0      BMW    M4   280
1     AUDI    A3   220
2  MUSTANG    GT   350